channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - cadquery=2.1
  - pip:
    - jupyter-cadquery==2.0.0
    - git+https://github.com/bernhard-42/cadquery-massembly