channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - cadquery=2.1
  - matplotlib=3.3
  - pip:
      - jupyter-cadquery==3.0.0rc0
      - cadquery-massembly~=0.9
      - pyquaternion~=0.9.9
